import CONSTANTS from '../constants/constants';

export default {
  [`${CONSTANTS.ACTIONS.STAND}${CONSTANTS.DIRECTIONS.LEFT}`]: ['bearWalkLeft7'],
  [`${CONSTANTS.ACTIONS.STAND}${CONSTANTS.DIRECTIONS.RIGHT}`]: ['bearWalkRight7'],
  [`${CONSTANTS.ACTIONS.STAND}${CONSTANTS.DIRECTIONS.UP}`]: ['bearWalkUp7'],
  [`${CONSTANTS.ACTIONS.STAND}${CONSTANTS.DIRECTIONS.DOWN}`]: ['bearWalkDown6'],
  [`${CONSTANTS.ACTIONS.WALK}${CONSTANTS.DIRECTIONS.LEFT}`]: [
    'bearWalkLeft1',
    'bearWalkLeft2',
    'bearWalkLeft3',
    'bearWalkLeft4',
    'bearWalkLeft5',
    'bearWalkLeft6',
    'bearWalkLeft7',
  ],
  [`${CONSTANTS.ACTIONS.WALK}${CONSTANTS.DIRECTIONS.UP}`]: [
    'bearWalkUp1',
    'bearWalkUp2',
    'bearWalkUp3',
    'bearWalkUp4',
    'bearWalkUp5',
    'bearWalkUp6',
    'bearWalkUp7',
  ],
  [`${CONSTANTS.ACTIONS.WALK}${CONSTANTS.DIRECTIONS.RIGHT}`]: [
    'bearWalkRight1',
    'bearWalkRight2',
    'bearWalkRight3',
    'bearWalkRight4',
    'bearWalkRight5',
    'bearWalkRight6',
    'bearWalkRight7',
  ],
  [`${CONSTANTS.ACTIONS.WALK}${CONSTANTS.DIRECTIONS.DOWN}`]: [
    'bearWalkDown1',
    'bearWalkDown2',
    'bearWalkDown3',
    'bearWalkDown4',
    'bearWalkDown5',
    'bearWalkDown5',
    'bearWalkDown6',
  ],
  [CONSTANTS.ACTIONS.MINE]: [
    'bearMineDown1',
    'bearMineDown2',
    'bearMineDown2',
    'bearMineDown1',
    'bearMineDown2',
    'bearMineDown2',
    'bearWalkRight7',
  ],
};
