import CONSTANTS from '../constants/constants';

export default {
  [`${CONSTANTS.ACTIONS.STAND}${CONSTANTS.DIRECTIONS.LEFT}`]: [
    'dogLeft',
  ],
  [`${CONSTANTS.ACTIONS.STAND}${CONSTANTS.DIRECTIONS.RIGHT}`]: [
    'dogRight',
  ],
  [`${CONSTANTS.ACTIONS.STAND}${CONSTANTS.DIRECTIONS.UP}`]: [
    'dogUp',
  ],
  [`${CONSTANTS.ACTIONS.STAND}${CONSTANTS.DIRECTIONS.DOWN}`]: [
    'dogDown',
  ],
  [`${CONSTANTS.ACTIONS.WALK}${CONSTANTS.DIRECTIONS.LEFT}`]: [
    'walkLeft1',
    'walkLeft2',
    'walkLeft3',
    'walkLeft4',
    'walkLeft5',
    'walkLeft6',
    'walkLeft7',
    'walkLeft8',
    'walkLeft9',
    'walkLeft10',
    'walkLeft11',
  ],
  [`${CONSTANTS.ACTIONS.WALK}${CONSTANTS.DIRECTIONS.UP}`]: [
    'walkUp1',
    'walkUp2',
    'walkUp3',
    'walkUp4',
    'walkUp5',
    'walkUp6',
    'walkUp7',
    'walkUp8',
    'walkUp9',
    'walkUp10',
    'walkUp11',
    'walkUp12',
  ],
  [`${CONSTANTS.ACTIONS.WALK}${CONSTANTS.DIRECTIONS.RIGHT}`]: [
    'walkRight1',
    'walkRight2',
    'walkRight3',
    'walkRight4',
    'walkRight5',
    'walkRight6',
    'walkRight7',
    'walkRight8',
    'walkRight9',
    'walkRight10',
    'walkRight11',
    'walkRight12',
    'walkRight13',
  ],
  [`${CONSTANTS.ACTIONS.WALK}${CONSTANTS.DIRECTIONS.DOWN}`]: [
    'walkDown1',
    'walkDown2',
    'walkDown3',
    'walkDown4',
    'walkDown5',
    'walkDown6',
    'walkDown7',
    'walkDown8',
    'walkDown9',
    'walkDown10',
  ],
  [CONSTANTS.ACTIONS.DEMINE]: [
    'demineDown1',
    'demineDown2',
    'demineDown3',
    'demineDown4',
    'demineDown5',
    'demineDown6',
    'demineDown7',
  ],
  [CONSTANTS.ACTIONS.BITE]: [
    'dogBite0',
    'dogBite0_1',
    'dogBite0_2',
    'dogBite0_3',
    'dogBite0_4',
  ],
};
